Refactor: refactor client
bytecraftoy/timesheets-backend pull request #4
Opened 2021-06-10 08:09 UTC by elmann

Added more specific http status codes for client methods.
ClientController.add() now uses a body parameter instead of query parameters.
Tests updated accordingly, and some refactoring done to facilitate these changes.

2021-06-10 13:21 UTC, anttiahonen requested changes

2021-06-10 13:21 UTC, anttiahonen commented on app/domain/services/ClientRepository.scala
>      if (client.name.isEmpty) {
Tässä voisi wrapata nämä validaatiot omaan apufunktioon, jolloin tässä kutsuttaisiin vain `validate(client)`

2021-06-10 13:21 UTC, anttiahonen commented on app/domain/services/ClientRepository.scala
> +      throw new IllegalArgumentException(msg)
Tässä voisi luoda jonkun domainin sisällä olevan exception luokan (esim InvalidDataException), joka muunnettaisiin controllerissa 422 statukseksi:

IllegalArgumentException --> 400 muunnos on mun mielestä hyvä. Se kapturoi 400:sen semantiikan.

Itse suosin 422 statusta kun validoidaan input parametreja ja ne eivät täyty semanttisia vaatimuksia. Täällä lisää aiheesta:

https://stackoverflow.com/a/52363900

Myös 400 olisi sinäänsä oikea status-koodi nykypäivänä, mutta 400 on "yleislaari", jonne sataa monia asioita. Siksi tarkempi 422 on ainakin omaan makuuni parempi

2021-06-10 13:21 UTC, anttiahonen commented on app/domain/services/ClientRepository.scala
>        logger.error(msg)
Error-lokitus on parempi keskittää tuonne ulkoreunalla web-apille.

Hyvä flow on tämänkaltainen:

1. Luo järkevä virheviesti
2. Heitä se exceptionin sisällä eteenpäin domainista / persistence/daosta
3. Nappaa "ulkoreunalla" eli controllerissa tai controllerien keskitetyssä exception handlerissa virheet. Tässä tapauksessa controller on hyvä, kuten tähänkin asti tehty. Katsotaan myöhemmin saadaanko keskitetty handler
4. Lokita virhe `logger.error(exception.message, exception)` <-- ensimäinen osuus printtaa meidän määritelemän virheviestin server lokille, toinen oksentaa stack tracen
4. Muunna tietyt virheet halutuiksi http status-koodin omaaviksi virheiksi ja heitä/palauta ne ulkomaailmalle.
5. Älä päästä liikaa sisäistä tietoa ulospäin serialisoidussa virhe-formaatissa

2021-06-10 13:21 UTC, anttiahonen commented on app/web/controllers/ClientController.scala
> +        case _: JdbcSQLException         => Conflict("Email already in use")
JdbcSQLException voi tulla monesta asiasta. Ehkä olisi parempi napata tuo exception jo daossa kiinni. Siellä voisi tutkia että onko virheen viestissä haluttu tieto (esim unique constraint violation) ja sen jälkeen muuntaa tuo domain-paketin alla olevaksi virheeksi. Esimerkiksi UniqueViolationException.

Sitten täällä controller tasolla napattaisiinkin vain UniqueViolationException tuon jdbc sijasta, sillä jdbc on kovin generaali ja sitä ei voi aina muuntaa 409 status-koodille

2021-06-10 13:21 UTC, anttiahonen commented on test/controllers/ClientControllerSpec.scala
> +      val jsonString =
Parempi rakentaa testidata DTO:n avulla, joka serialisoidaan sitten jsoniksi kutsuun. Näin ollen meillä säilyy tyypitys mukana, jos tuo endpointin vastaanottama body muuttaisi muotoaan. Tälläinen dynaaminen stringi kun ei compiler apua saa

2021-06-10 13:21 UTC, anttiahonen commented on test/controllers/ClientControllerSpec.scala
> +    ): String = s"""{"name": "$clientName","email": "$clientEmail"}"""
rakenna DTO avulla testidata

2021-06-10 13:21 UTC, anttiahonen commented on test/controllers/ClientControllerSpec.scala
> +        jsonStringForPostBody(
Käytä DTO tässä

2021-06-10 13:21 UTC, anttiahonen commented on test/controllers/ClientControllerSpec.scala
> +      val json = Json.parse(jsonStringForPostBody("", ""))
dto:lla testidatan rakennus

2021-06-10 13:22 UTC, anttiahonen commented on app/web/controllers/ClientController.scala
> +        case _: JdbcSQLException         => Conflict
Annoin tähän myöhemmin parempaa infoa, eli tuon jdbc exceptionin voi catchaa jo daossa ja muuntaa hallituksi domain exceptioniksi (jos conflicti syntyy). Muutoin Jdbc exceptionin voi heittää eteenpäin ja antaa sen muuntautu 500-status koodilla olevaksi virheeksi

2021-06-10 13:30 UTC, anttiahonen commented
Pure-domain ajattelu on tässä oikein. Hyviä muutoksia, vielä voidaan nytkäyttää niitä napsu eteenpäin niin alkaa oleen hyvällä mallilla tämä käsittely :)

2021-06-11 04:27 UTC, jorilytter commented on app/web/dto/ClientDTO.scala
> +object AddClientDTO {
tää on nimenomaan tapa companion objectia scalassa :+1:

2021-06-11 04:27 UTC, jorilytter commented on app/web/dto/ClientDTO.scala
> +object AddClientDTO {
sivuhuomiona, laittaisin tyhjän rivin case classin ja objectin väliin, niin on helpompi erottaa, missä yksi loppuu ja toinen alkaa :smile:

2021-06-11 04:38 UTC, jorilytter commented on app/web/dto/ClientMapper.scala
> +@ImplementedBy(classOf[DevelopmentClientMapper])
Tapoja on varmasti monta, mutta itse käyttäisin objectia. Tällöin kyseessä olisi singleton, jolla on staattinen funktio. Myöskin package object voisi olla vaihtoehto, https://docs.scala-lang.org/tour/package-objects.html.
Package objectista pääseekin kivasti aasinsiltana lisähuomioon, että pitäiskö tämän toteutuksen itse asiassa olla pakettihiearkiassa yhtä tasoa ylempänä eli `web`-paketissa, koska tämähän nyt ei varsinaisesti ei ole DTO-liitännäinen asia vaikkakin funktio ottaa dto:n parametrina?

2021-06-11 06:40 UTC, elmann commented on app/web/controllers/ClientController.scala
> +        case unhandled: Exception =>
Viimeisimmässä commitissa nämä unhandled:Exception -kaappaukset on otettu pois, jolloin:
1. Playlta tulee ulos automaattisesti 500, ja stack trace (vain development modessa)
2. stack trace näkyy sbt shellissä, mutta lokiin ei näytä menevän.

Näillä toiveilla taitaa siis sittenkin olla hyvä käsitellä exception => 500 itse.
Play frameworkin oma esimerkki: https://www.playframework.com/documentation/2.8.x/ScalaLogging
```
class Application @Inject() (val accessLoggingAction: AccessLoggingAction, cc: ControllerComponents)
    extends AbstractController(cc) {
  val logger = Logger(this.getClass())

  def index = accessLoggingAction {
    try {
      val result = riskyCalculation
      Ok(s"Result=$result")
    } catch {
      case t: Throwable => {
        logger.error("Exception with riskyCalculation", t)
        InternalServerError("Error in calculation: " + t.getMessage())
      }
    }
  }
}
```

2021-06-14 07:09 UTC, elmann commented on app/web/dto/ClientMapper.scala
> +@ImplementedBy(classOf[DevelopmentClientMapper])
Näitä mapper-objekteja voi hyvinkin tulla paljon lisää, olisiko silloin web/mappers hyvä paikka tälle?

2021-06-14 07:40 UTC, jorilytter commented on app/web/dto/ClientMapper.scala
> +@ImplementedBy(classOf[DevelopmentClientMapper])
ei oo varmaankaan yhtä oikeeta vastausta eli tässä vaiheessa web.mappers on varmaankin ihan hyvä, ainahan näitä voi liikutella eri paketteihin, jos tulee tarve

2021-06-15 04:01 UTC, jorilytter submitted a review, later dismissed

2021-06-15 06:43 UTC, anttiahonen commented
Kokonaisuudessaan jo oikein hyvä, vielä muutamia commitin yhdistelyitä kuten puhuttiin ja sit on bueno

2021-06-15 06:59 UTC, anttiahonen approved these changes
Good work

2021-06-15 07:00 UTC, merged